// Generated by CoffeeScript 1.3.3
(function() {
  var Fs, Pg,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Fs = require('fs');

  Pg = (function(_super) {

    __extends(Pg, _super);

    function Pg() {
      return Pg.__super__.constructor.apply(this, arguments);
    }

    Pg.prototype.execFile = function(filename, cb) {
      var _this = this;
      return Fs.readFile(filename, 'utf8', function(err, data) {
        if (err) {
          return cb(err);
        }
        return _this.exec(data, cb);
      });
    };

    return Pg;

  })(Postgresql);

}).call(this);
